### ISSUE TITLE
K8 UAT environment for EOS repository

### ISSUE THREAD

**Issue by Shwetik** [Dreadlimbo/EOS#3]
Hi all, 

We need to create K8 cluster UAT setup for our EOS repo.

Preferred environment - Kind or minikube

Thanks.

**Comment by Dreadlimbo** [comment]
Hey @Shwetik,

Can you please share a basic structure for K8 cluster preferably on KIND please.

Thanks.

**Comment by Dreadlimbo** [comment]
#5 was merged sucessfully. Hence closing this.
